### ISSUE TITLE
[Question] Does categorical-encoder work with numpy?

### ISSUE THREAD

**Issue by bozhang0504** [scikit-learn-contrib/categorical-encoding#66] opened 2018-05-03 22:14 UTC
I tried with Leave One Out encoder, I got error when try to input numpy array. Does it work with Pandas dataframe only?

**Comment by wdm0006** [comment] 2018-05-13 15:02
Nope, works with both. 

Do you have a specific error of some kind you can post?

**Comment by bozhang0504** [comment] 2018-05-14 01:10
Sorry, I just tested again, my original question is wrong.

The question should be - it doesn't work with Pandas Series.

Here is test code:
```
import category_encoders as ce

loo_enc = ce.LeaveOneOutEncoder()

df = pd.DataFrame({'cat_col': ['A','A','B','B','B','C'],  'target': [0, 1, 0, 1, 0, 1]})
```

I tested with numpy nd.array there is no problem here.
```
loo_enc.fit_transform(df['cat_col'].values, df['target'])
```

Then I tested with pandas dataframe with selected column.
```
loo_enc.fit_transform(df['cat_col'], df['target'])
```
Then I got error:
```
ValueError                                Traceback (most recent call last)
<ipython-input-44-9a42b847986a> in <module>()
----> 1 loo_enc.fit_transform(df['cat_col'], df['target'])

/anaconda/lib/python3.6/site-packages/sklearn/base.py in fit_transform(self, X, y, **fit_params)
    518         else:
    519             # fit method of arity 2 (supervised transformation)
--> 520             return self.fit(X, y, **fit_params).transform(X)
    521 
    522 

/anaconda/lib/python3.6/site-packages/category_encoders/leave_one_out.py in fit(self, X, y, **kwargs)
    121 
    122         # first check the type
--> 123         X = convert_input(X)
    124         y = pd.Series(y, name='target')
    125         assert X.shape[0] == y.shape[0]

/anaconda/lib/python3.6/site-packages/category_encoders/utils.py in convert_input(X)
     26             X = pd.DataFrame(X.todense())
     27         else:
---> 28             raise ValueError('Unexpected input type: %s' % (str(type(X))))
     29 
     30         X = X.apply(lambda x: pd.to_numeric(x, errors='ignore'))

ValueError: Unexpected input type: <class 'pandas.core.series.Series'>
```

**Comment by wdm0006** [comment] 2018-05-14 01:37
Correct, it does not work with series. 

Normally here you'd pass a dataframe and perhaps specify certain columns to use with the "cols" param. Any reason you can't use a dataframe?

**Comment by bozhang0504** [comment] 2018-05-14 05:09
Thank for you quick reply.

I am building a pipeline with  [sklearn_pandas](https://github.com/scikit-learn-contrib/sklearn-pandas) package's `DataFrameMapper`.

The pipeline is used to generate PMML file using [sklearn2PMML](https://github.com/jpmml/sklearn2pmml).

Here is an example from `sklearn2PMML`'s documentation with a little tweak.

```
from sklearn_pandas import DataFrameMapper
from sklearn.linear_model import LogisticRegression
from sklearn2pmml.decoration import CategoricalDomain
from sklearn2pmml.pipeline import PMMLPipeline

pipeline = PMMLPipeline([
	("mapper", DataFrameMapper([
		(["cat_colA", "cat_colB", "cat_colC"], [CategoricalDomain(), LeaveOneOutEncoder()])
	])),
	("classifier", LogisticRegression())
])
```
Error happened at the mapper step. A Pandas series will be passed to  `LeaveOneOutEncoder()` for each column.

Hope this answers your question. 

It would be great if you can provide compatibility for series. Thank you!

**Comment by wdm0006** [comment] 2018-05-29 01:19
Closing this as it's not a bug, we will take a look at adding support for series in a future release. If you're interested in working on this let me know.

**Closed by wdm0006** 2018-05-29 01:19 UTC
